### ISSUE TITLE
files not deleted

### ISSUE THREAD

**Issue by hefekranz** [cpina/github-action-push-to-another-repository#43] opened 2021-11-08 19:03 UTC
Hi there and thanks for creating this action.
I realized that (maybe for a while, maybe since a recent change) deleted files aren't included in the commit to the dest. repository. It looks like this has something to do with the new TARGET_DIRECTORY, if none is set, it wont remove the content  from the root. And cp will just add new files.
I didn't really want to touch the TARGET_DIRECTORY logic, but solved it with rsync.
Maybe this is just us and our workflow, but if you get more issues like this, here is a fork
https://github.com/spiribo/github-action-push-to-another-repository

Cheers,
Levin

**Comment by cpina** [comment] 2021-11-08 21:40
Hi Levin,
Thanks for letting me know, I'll check this the next days.
(good idea using rsync for this :-) )

Cheers,
Carles

**Comment by tc-imba** [comment] 2021-12-08 22:05
same issue

**Comment by cpina** [comment] 2021-12-08 23:05
@hefekranz , @tc-imba , @Belax8: the issue is now fixed (as far as I've tested it!) in the `main` branch.

At some point I should write tests for the small action.

Apologies for the slow delay and thanks for pinging here around, it was my to do list for two weeks :-)

Any problems let me know please in this issue or a new one.

**Closed by cpina** 2021-12-08 23:05 UTC
