### ISSUE TITLE
Option to create the target directory if it doesn't exist

### ISSUE THREAD

**Issue by nedbat** [cpina/github-action-push-to-another-repository#52] opened 2021-12-28 11:54 UTC
This is available in https://github.com/sebastian-palma/github-action-push-to-another-repository.  Can we add it to this repo to consolidate the functionality?

**Comment by cpina** [comment] 2021-12-28 20:37
I'll look into it, hopefully over the next 7 days :-) I'll comment here with any update. Thanks for pinging :-)

**Comment by cpina** [comment] 2022-01-22 21:51
I want to implement this but first I want to write tests for the action to avoid regressions. Thanks for the idea!

**Comment by cpina** [comment] 2022-09-05 22:52
Thanks, I've decided that for now I'll leave it as "out of scope" (since no tests yet, and that the action reports the problem and the branch can be created before the action is used, at least in the most common cases).

**Closed by cpina** 2022-09-05 22:52 UTC
Labels: enhancement
